project_path: .
model_name: default
read_format: parquet
ddconfig_path: PLEASE FILL

selected_columns: null
target_columns: [itemValue]
target_column_types:
  itemValue: real

seq_length: 25
inference_batch_size: 10

export_onnx: true

model_spec:
  d_model: 64
  nhead: 4
  d_hid: 64
  nlayers: 4
training_spec:
  device: cpu
  epochs: 1000
  iter_save: 100
  batch_size: 20
  log_interval: 10
  lr: 0.0008
  accumulation_steps: 1
  dropout: 0.2
  criterion:
    Precipitation: MSELoss
  optimizer:
    name: AdamW
  scheduler:
    name: StepLR
    step_size: 100
    gamma: 0.99
  continue_training: false